name: NPM Custom Action
decription: Installing and Caching NPM packages

inputs:
  path-of-cache:
    description: 'The path to cache'
    required: true

#outputs:

runs:
  using: composite
  steps:
    - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ${{ inputs.path-of-cache }}
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install
      shell: bash

